# Copyright 2018 EPS Universidad Autónoma de Madrid.
# Copyright and related rights are licensed under the Solderpad Hardware
# License, Version 0.51 (the “License”); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
# or agreed to in writing, software, hardware and materials distributed under
# this License is distributed on an “AS IS” BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

set_property PACKAGE_PIN U14 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 83.333 -name board_clk -add [get_ports clk]

set_property PACKAGE_PIN T12 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN U12 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]

set_property PACKAGE_PIN U7 [get_ports ext_tck_i]
set_property IOSTANDARD LVCMOS33 [get_ports ext_tck_i]
set_property PACKAGE_PIN V7 [get_ports ext_tms_i]
set_property IOSTANDARD LVCMOS33 [get_ports ext_tms_i]
set_property PACKAGE_PIN T9 [get_ports ext_tdi_i]
set_property IOSTANDARD LVCMOS33 [get_ports ext_tdi_i]
set_property PACKAGE_PIN U10 [get_ports ext_tdo_o]
set_property IOSTANDARD LVCMOS33 [get_ports ext_tdo_o]
set_property PACKAGE_PIN Y7 [get_ports ext_trstn_i]
set_property IOSTANDARD LVCMOS33 [get_ports ext_trstn_i]





set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_arready]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_arvalid]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awready]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awvalid]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_bready]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_bvalid]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rlast]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rready]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rvalid]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wlast]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wready]
set_property MARK_DEBUG true [get_nets zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wvalid]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[0]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[1]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[2]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[3]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[4]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[5]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[6]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[7]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[8]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[9]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[10]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[11]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[12]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[13]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[14]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[15]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[16]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[17]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[18]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[19]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[20]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[21]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[22]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[23]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[24]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[25]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[26]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[27]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[28]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[29]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[30]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[31]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[0]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[1]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[2]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[3]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[4]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[5]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[6]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[7]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[8]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[9]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[10]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[11]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[12]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[13]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[14]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[15]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[16]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[17]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[18]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[19]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[20]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[21]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[22]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[23]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[24]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[25]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[26]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[27]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[28]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[29]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[30]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[31]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[0]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[1]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[2]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[3]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[4]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[5]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[6]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[7]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[8]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[9]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[10]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[11]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[12]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[13]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[14]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[15]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[16]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[17]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[18]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[19]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[20]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[21]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[22]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[23]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[24]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[25]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[26]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[27]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[28]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[29]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[30]}]
set_property MARK_DEBUG true [get_nets {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[31]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list host_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {S_AXI_GP\\.aw_id[0]} {S_AXI_GP\\.aw_id[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {M_AXI_ACP\\.w_data[0]} {M_AXI_ACP\\.w_data[1]} {M_AXI_ACP\\.w_data[2]} {M_AXI_ACP\\.w_data[3]} {M_AXI_ACP\\.w_data[4]} {M_AXI_ACP\\.w_data[5]} {M_AXI_ACP\\.w_data[6]} {M_AXI_ACP\\.w_data[7]} {M_AXI_ACP\\.w_data[8]} {M_AXI_ACP\\.w_data[9]} {M_AXI_ACP\\.w_data[10]} {M_AXI_ACP\\.w_data[11]} {M_AXI_ACP\\.w_data[12]} {M_AXI_ACP\\.w_data[13]} {M_AXI_ACP\\.w_data[14]} {M_AXI_ACP\\.w_data[15]} {M_AXI_ACP\\.w_data[16]} {M_AXI_ACP\\.w_data[17]} {M_AXI_ACP\\.w_data[18]} {M_AXI_ACP\\.w_data[19]} {M_AXI_ACP\\.w_data[20]} {M_AXI_ACP\\.w_data[21]} {M_AXI_ACP\\.w_data[22]} {M_AXI_ACP\\.w_data[23]} {M_AXI_ACP\\.w_data[24]} {M_AXI_ACP\\.w_data[25]} {M_AXI_ACP\\.w_data[26]} {M_AXI_ACP\\.w_data[27]} {M_AXI_ACP\\.w_data[28]} {M_AXI_ACP\\.w_data[29]} {M_AXI_ACP\\.w_data[30]} {M_AXI_ACP\\.w_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {S_AXI_GP\\.ar_id[0]} {S_AXI_GP\\.ar_id[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {S_AXI_GP\\.b_id[0]} {S_AXI_GP\\.b_id[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {M_AXI_ACP\\.r_data[0]} {M_AXI_ACP\\.r_data[1]} {M_AXI_ACP\\.r_data[2]} {M_AXI_ACP\\.r_data[3]} {M_AXI_ACP\\.r_data[4]} {M_AXI_ACP\\.r_data[5]} {M_AXI_ACP\\.r_data[6]} {M_AXI_ACP\\.r_data[7]} {M_AXI_ACP\\.r_data[8]} {M_AXI_ACP\\.r_data[9]} {M_AXI_ACP\\.r_data[10]} {M_AXI_ACP\\.r_data[11]} {M_AXI_ACP\\.r_data[12]} {M_AXI_ACP\\.r_data[13]} {M_AXI_ACP\\.r_data[14]} {M_AXI_ACP\\.r_data[15]} {M_AXI_ACP\\.r_data[16]} {M_AXI_ACP\\.r_data[17]} {M_AXI_ACP\\.r_data[18]} {M_AXI_ACP\\.r_data[19]} {M_AXI_ACP\\.r_data[20]} {M_AXI_ACP\\.r_data[21]} {M_AXI_ACP\\.r_data[22]} {M_AXI_ACP\\.r_data[23]} {M_AXI_ACP\\.r_data[24]} {M_AXI_ACP\\.r_data[25]} {M_AXI_ACP\\.r_data[26]} {M_AXI_ACP\\.r_data[27]} {M_AXI_ACP\\.r_data[28]} {M_AXI_ACP\\.r_data[29]} {M_AXI_ACP\\.r_data[30]} {M_AXI_ACP\\.r_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {M_AXI_ACP\\.w_strb[0]} {M_AXI_ACP\\.w_strb[1]} {M_AXI_ACP\\.w_strb[2]} {M_AXI_ACP\\.w_strb[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {M_AXI_GP\\.r_data[0]} {M_AXI_GP\\.r_data[1]} {M_AXI_GP\\.r_data[2]} {M_AXI_GP\\.r_data[3]} {M_AXI_GP\\.r_data[4]} {M_AXI_GP\\.r_data[5]} {M_AXI_GP\\.r_data[6]} {M_AXI_GP\\.r_data[7]} {M_AXI_GP\\.r_data[8]} {M_AXI_GP\\.r_data[9]} {M_AXI_GP\\.r_data[10]} {M_AXI_GP\\.r_data[11]} {M_AXI_GP\\.r_data[12]} {M_AXI_GP\\.r_data[13]} {M_AXI_GP\\.r_data[14]} {M_AXI_GP\\.r_data[15]} {M_AXI_GP\\.r_data[16]} {M_AXI_GP\\.r_data[17]} {M_AXI_GP\\.r_data[18]} {M_AXI_GP\\.r_data[19]} {M_AXI_GP\\.r_data[20]} {M_AXI_GP\\.r_data[21]} {M_AXI_GP\\.r_data[22]} {M_AXI_GP\\.r_data[23]} {M_AXI_GP\\.r_data[24]} {M_AXI_GP\\.r_data[25]} {M_AXI_GP\\.r_data[26]} {M_AXI_GP\\.r_data[27]} {M_AXI_GP\\.r_data[28]} {M_AXI_GP\\.r_data[29]} {M_AXI_GP\\.r_data[30]} {M_AXI_GP\\.r_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {S_AXI_GP\\.ar_addr[0]} {S_AXI_GP\\.ar_addr[1]} {S_AXI_GP\\.ar_addr[2]} {S_AXI_GP\\.ar_addr[3]} {S_AXI_GP\\.ar_addr[4]} {S_AXI_GP\\.ar_addr[5]} {S_AXI_GP\\.ar_addr[6]} {S_AXI_GP\\.ar_addr[7]} {S_AXI_GP\\.ar_addr[8]} {S_AXI_GP\\.ar_addr[9]} {S_AXI_GP\\.ar_addr[10]} {S_AXI_GP\\.ar_addr[11]} {S_AXI_GP\\.ar_addr[12]} {S_AXI_GP\\.ar_addr[13]} {S_AXI_GP\\.ar_addr[14]} {S_AXI_GP\\.ar_addr[15]} {S_AXI_GP\\.ar_addr[16]} {S_AXI_GP\\.ar_addr[17]} {S_AXI_GP\\.ar_addr[18]} {S_AXI_GP\\.ar_addr[19]} {S_AXI_GP\\.ar_addr[20]} {S_AXI_GP\\.ar_addr[21]} {S_AXI_GP\\.ar_addr[22]} {S_AXI_GP\\.ar_addr[23]} {S_AXI_GP\\.ar_addr[24]} {S_AXI_GP\\.ar_addr[25]} {S_AXI_GP\\.ar_addr[26]} {S_AXI_GP\\.ar_addr[27]} {S_AXI_GP\\.ar_addr[28]} {S_AXI_GP\\.ar_addr[29]} {S_AXI_GP\\.ar_addr[30]} {S_AXI_GP\\.ar_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {S_AXI_GP\\.aw_addr[0]} {S_AXI_GP\\.aw_addr[1]} {S_AXI_GP\\.aw_addr[2]} {S_AXI_GP\\.aw_addr[3]} {S_AXI_GP\\.aw_addr[4]} {S_AXI_GP\\.aw_addr[5]} {S_AXI_GP\\.aw_addr[6]} {S_AXI_GP\\.aw_addr[7]} {S_AXI_GP\\.aw_addr[8]} {S_AXI_GP\\.aw_addr[9]} {S_AXI_GP\\.aw_addr[10]} {S_AXI_GP\\.aw_addr[11]} {S_AXI_GP\\.aw_addr[12]} {S_AXI_GP\\.aw_addr[13]} {S_AXI_GP\\.aw_addr[14]} {S_AXI_GP\\.aw_addr[15]} {S_AXI_GP\\.aw_addr[16]} {S_AXI_GP\\.aw_addr[17]} {S_AXI_GP\\.aw_addr[18]} {S_AXI_GP\\.aw_addr[19]} {S_AXI_GP\\.aw_addr[20]} {S_AXI_GP\\.aw_addr[21]} {S_AXI_GP\\.aw_addr[22]} {S_AXI_GP\\.aw_addr[23]} {S_AXI_GP\\.aw_addr[24]} {S_AXI_GP\\.aw_addr[25]} {S_AXI_GP\\.aw_addr[26]} {S_AXI_GP\\.aw_addr[27]} {S_AXI_GP\\.aw_addr[28]} {S_AXI_GP\\.aw_addr[29]} {S_AXI_GP\\.aw_addr[30]} {S_AXI_GP\\.aw_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 2 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {S_AXI_GP\\.aw_burst[0]} {S_AXI_GP\\.aw_burst[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 31 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {M_AXI_GP\\.ar_addr[1]} {M_AXI_GP\\.ar_addr[2]} {M_AXI_GP\\.ar_addr[3]} {M_AXI_GP\\.ar_addr[4]} {M_AXI_GP\\.ar_addr[5]} {M_AXI_GP\\.ar_addr[6]} {M_AXI_GP\\.ar_addr[7]} {M_AXI_GP\\.ar_addr[8]} {M_AXI_GP\\.ar_addr[9]} {M_AXI_GP\\.ar_addr[10]} {M_AXI_GP\\.ar_addr[11]} {M_AXI_GP\\.ar_addr[12]} {M_AXI_GP\\.ar_addr[13]} {M_AXI_GP\\.ar_addr[14]} {M_AXI_GP\\.ar_addr[15]} {M_AXI_GP\\.ar_addr[16]} {M_AXI_GP\\.ar_addr[17]} {M_AXI_GP\\.ar_addr[18]} {M_AXI_GP\\.ar_addr[19]} {M_AXI_GP\\.ar_addr[20]} {M_AXI_GP\\.ar_addr[21]} {M_AXI_GP\\.ar_addr[22]} {M_AXI_GP\\.ar_addr[23]} {M_AXI_GP\\.ar_addr[24]} {M_AXI_GP\\.ar_addr[25]} {M_AXI_GP\\.ar_addr[26]} {M_AXI_GP\\.ar_addr[27]} {M_AXI_GP\\.ar_addr[28]} {M_AXI_GP\\.ar_addr[29]} {M_AXI_GP\\.ar_addr[30]} {M_AXI_GP\\.ar_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 4 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {S_AXI_GP\\.w_strb[0]} {S_AXI_GP\\.w_strb[1]} {S_AXI_GP\\.w_strb[2]} {S_AXI_GP\\.w_strb[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {S_AXI_GP\\.w_data[0]} {S_AXI_GP\\.w_data[1]} {S_AXI_GP\\.w_data[2]} {S_AXI_GP\\.w_data[3]} {S_AXI_GP\\.w_data[4]} {S_AXI_GP\\.w_data[5]} {S_AXI_GP\\.w_data[6]} {S_AXI_GP\\.w_data[7]} {S_AXI_GP\\.w_data[8]} {S_AXI_GP\\.w_data[9]} {S_AXI_GP\\.w_data[10]} {S_AXI_GP\\.w_data[11]} {S_AXI_GP\\.w_data[12]} {S_AXI_GP\\.w_data[13]} {S_AXI_GP\\.w_data[14]} {S_AXI_GP\\.w_data[15]} {S_AXI_GP\\.w_data[16]} {S_AXI_GP\\.w_data[17]} {S_AXI_GP\\.w_data[18]} {S_AXI_GP\\.w_data[19]} {S_AXI_GP\\.w_data[20]} {S_AXI_GP\\.w_data[21]} {S_AXI_GP\\.w_data[22]} {S_AXI_GP\\.w_data[23]} {S_AXI_GP\\.w_data[24]} {S_AXI_GP\\.w_data[25]} {S_AXI_GP\\.w_data[26]} {S_AXI_GP\\.w_data[27]} {S_AXI_GP\\.w_data[28]} {S_AXI_GP\\.w_data[29]} {S_AXI_GP\\.w_data[30]} {S_AXI_GP\\.w_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 2 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {S_AXI_GP\\.r_id[0]} {S_AXI_GP\\.r_id[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {S_AXI_GP\\.r_data[0]} {S_AXI_GP\\.r_data[1]} {S_AXI_GP\\.r_data[2]} {S_AXI_GP\\.r_data[3]} {S_AXI_GP\\.r_data[4]} {S_AXI_GP\\.r_data[5]} {S_AXI_GP\\.r_data[6]} {S_AXI_GP\\.r_data[7]} {S_AXI_GP\\.r_data[8]} {S_AXI_GP\\.r_data[9]} {S_AXI_GP\\.r_data[10]} {S_AXI_GP\\.r_data[11]} {S_AXI_GP\\.r_data[12]} {S_AXI_GP\\.r_data[13]} {S_AXI_GP\\.r_data[14]} {S_AXI_GP\\.r_data[15]} {S_AXI_GP\\.r_data[16]} {S_AXI_GP\\.r_data[17]} {S_AXI_GP\\.r_data[18]} {S_AXI_GP\\.r_data[19]} {S_AXI_GP\\.r_data[20]} {S_AXI_GP\\.r_data[21]} {S_AXI_GP\\.r_data[22]} {S_AXI_GP\\.r_data[23]} {S_AXI_GP\\.r_data[24]} {S_AXI_GP\\.r_data[25]} {S_AXI_GP\\.r_data[26]} {S_AXI_GP\\.r_data[27]} {S_AXI_GP\\.r_data[28]} {S_AXI_GP\\.r_data[29]} {S_AXI_GP\\.r_data[30]} {S_AXI_GP\\.r_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[0]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[1]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[2]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[3]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[4]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[5]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[6]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[7]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[8]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[9]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[10]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[11]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[12]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[13]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[14]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[15]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[16]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[17]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[18]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[19]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[20]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[21]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[22]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[23]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[24]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[25]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[26]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[27]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[28]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[29]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[30]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_araddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[0]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[1]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[2]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[3]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[4]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[5]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[6]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[7]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[8]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[9]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[10]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[11]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[12]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[13]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[14]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[15]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[16]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[17]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[18]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[19]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[20]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[21]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[22]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[23]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[24]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[25]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[26]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[27]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[28]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[29]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[30]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awaddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[0]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[1]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[2]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[3]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[4]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[5]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[6]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[7]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[8]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[9]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[10]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[11]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[12]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[13]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[14]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[15]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[16]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[17]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[18]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[19]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[20]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[21]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[22]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[23]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[24]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[25]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[26]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[27]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[28]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[29]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[30]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 32 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[0]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[1]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[2]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[3]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[4]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[5]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[6]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[7]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[8]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[9]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[10]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[11]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[12]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[13]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[14]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[15]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[16]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[17]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[18]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[19]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[20]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[21]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[22]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[23]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[24]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[25]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[26]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[27]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[28]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[29]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[30]} {zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 32 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {M_AXI_ACP\\.aw_addr[0]} {M_AXI_ACP\\.aw_addr[1]} {M_AXI_ACP\\.aw_addr[2]} {M_AXI_ACP\\.aw_addr[3]} {M_AXI_ACP\\.aw_addr[4]} {M_AXI_ACP\\.aw_addr[5]} {M_AXI_ACP\\.aw_addr[6]} {M_AXI_ACP\\.aw_addr[7]} {M_AXI_ACP\\.aw_addr[8]} {M_AXI_ACP\\.aw_addr[9]} {M_AXI_ACP\\.aw_addr[10]} {M_AXI_ACP\\.aw_addr[11]} {M_AXI_ACP\\.aw_addr[12]} {M_AXI_ACP\\.aw_addr[13]} {M_AXI_ACP\\.aw_addr[14]} {M_AXI_ACP\\.aw_addr[15]} {M_AXI_ACP\\.aw_addr[16]} {M_AXI_ACP\\.aw_addr[17]} {M_AXI_ACP\\.aw_addr[18]} {M_AXI_ACP\\.aw_addr[19]} {M_AXI_ACP\\.aw_addr[20]} {M_AXI_ACP\\.aw_addr[21]} {M_AXI_ACP\\.aw_addr[22]} {M_AXI_ACP\\.aw_addr[23]} {M_AXI_ACP\\.aw_addr[24]} {M_AXI_ACP\\.aw_addr[25]} {M_AXI_ACP\\.aw_addr[26]} {M_AXI_ACP\\.aw_addr[27]} {M_AXI_ACP\\.aw_addr[28]} {M_AXI_ACP\\.aw_addr[29]} {M_AXI_ACP\\.aw_addr[30]} {M_AXI_ACP\\.aw_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 32 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {M_AXI_ACP\\.ar_addr[0]} {M_AXI_ACP\\.ar_addr[1]} {M_AXI_ACP\\.ar_addr[2]} {M_AXI_ACP\\.ar_addr[3]} {M_AXI_ACP\\.ar_addr[4]} {M_AXI_ACP\\.ar_addr[5]} {M_AXI_ACP\\.ar_addr[6]} {M_AXI_ACP\\.ar_addr[7]} {M_AXI_ACP\\.ar_addr[8]} {M_AXI_ACP\\.ar_addr[9]} {M_AXI_ACP\\.ar_addr[10]} {M_AXI_ACP\\.ar_addr[11]} {M_AXI_ACP\\.ar_addr[12]} {M_AXI_ACP\\.ar_addr[13]} {M_AXI_ACP\\.ar_addr[14]} {M_AXI_ACP\\.ar_addr[15]} {M_AXI_ACP\\.ar_addr[16]} {M_AXI_ACP\\.ar_addr[17]} {M_AXI_ACP\\.ar_addr[18]} {M_AXI_ACP\\.ar_addr[19]} {M_AXI_ACP\\.ar_addr[20]} {M_AXI_ACP\\.ar_addr[21]} {M_AXI_ACP\\.ar_addr[22]} {M_AXI_ACP\\.ar_addr[23]} {M_AXI_ACP\\.ar_addr[24]} {M_AXI_ACP\\.ar_addr[25]} {M_AXI_ACP\\.ar_addr[26]} {M_AXI_ACP\\.ar_addr[27]} {M_AXI_ACP\\.ar_addr[28]} {M_AXI_ACP\\.ar_addr[29]} {M_AXI_ACP\\.ar_addr[30]} {M_AXI_ACP\\.ar_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {M_AXI_ACP\\.ar_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {zynq_ps_wrapper_i/M_AXI_ACP\\.ar_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {M_AXI_ACP\\.aw_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {M_AXI_ACP\\.aw_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {M_AXI_ACP\\.b_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {M_AXI_ACP\\.b_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {M_AXI_ACP\\.r_last}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {M_AXI_ACP\\.r_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {M_AXI_ACP\\.r_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {M_AXI_ACP\\.w_last}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {M_AXI_ACP\\.w_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {M_AXI_ACP\\.w_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {M_AXI_GP\\.ar_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {M_AXI_GP\\.ar_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {M_AXI_GP\\.b_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {M_AXI_GP\\.b_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {M_AXI_GP\\.r_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {M_AXI_GP\\.r_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_bready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_bvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list zynq_ps_wrapper_i/zynq_ps_i/axi_interconnect_2/S00_AXI_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list {S_AXI_GP\\.ar_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
connect_debug_port u_ila_0/probe52 [get_nets [list {S_AXI_GP\\.ar_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
connect_debug_port u_ila_0/probe53 [get_nets [list {S_AXI_GP\\.aw_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
connect_debug_port u_ila_0/probe54 [get_nets [list {S_AXI_GP\\.aw_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property port_width 1 [get_debug_ports u_ila_0/probe55]
connect_debug_port u_ila_0/probe55 [get_nets [list {S_AXI_GP\\.b_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property port_width 1 [get_debug_ports u_ila_0/probe56]
connect_debug_port u_ila_0/probe56 [get_nets [list {S_AXI_GP\\.b_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property port_width 1 [get_debug_ports u_ila_0/probe57]
connect_debug_port u_ila_0/probe57 [get_nets [list {S_AXI_GP\\.r_last}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property port_width 1 [get_debug_ports u_ila_0/probe58]
connect_debug_port u_ila_0/probe58 [get_nets [list {S_AXI_GP\\.r_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
connect_debug_port u_ila_0/probe59 [get_nets [list {S_AXI_GP\\.r_valid}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
connect_debug_port u_ila_0/probe60 [get_nets [list {S_AXI_GP\\.w_last}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
connect_debug_port u_ila_0/probe61 [get_nets [list {S_AXI_GP\\.w_ready}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
connect_debug_port u_ila_0/probe62 [get_nets [list {S_AXI_GP\\.w_valid}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets host_clk]
